name: dev pull_request CI
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      - name: Eslint check
        run: npm run lint:fix

